---
common_home_directory: "{{ lookup('env', 'HOME') }}"
common_user_id: "{{ lookup('env', 'USER') }}"
common_directories:
    appimage: "{{ common_home_directory }}/Applications"
    local_bin: "{{ common_home_directory }}/.local/bin"
    projects: "{{ common_home_directory }}/Projects"
    config: "{{ common_home_directory }}/.config"
    ssh: "{{ common_home_directory }}/.ssh"
    ssh_socket: "{{ common_home_directory }}/.ssh/socket"
...
# vim: ft=yaml.ansible
